# Generated by Django 4.2 on 2023-05-23 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Occasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=128)),
                ('description', models.TextField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('recipe_ingredients', models.TextField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecipeOccasion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occasion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eat_fit_app.occasion')),
                ('recipe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eat_fit_app.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeIngredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('measure', models.CharField(max_length=64)),
                ('ingredients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eat_fit_app.ingredients')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eat_fit_app.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eat_fit_app.cuisine')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eat_fit_app.recipe')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eat_fit_app.category')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eat_fit_app.recipe')),
            ],
        ),
        migrations.AddField(
            model_name='occasion',
            name='recipes',
            field=models.ManyToManyField(related_name='occasions', through='eat_fit_app.RecipeOccasion', to='eat_fit_app.recipe'),
        ),
        migrations.AddField(
            model_name='ingredients',
            name='recipe',
            field=models.ManyToManyField(related_name='ingredients', through='eat_fit_app.RecipeIngredients', to='eat_fit_app.recipe'),
        ),
        migrations.AddField(
            model_name='cuisine',
            name='recipes',
            field=models.ManyToManyField(related_name='cuisines', through='eat_fit_app.RecipeCuisine', to='eat_fit_app.recipe'),
        ),
        migrations.AddField(
            model_name='category',
            name='recipes',
            field=models.ManyToManyField(related_name='categories', through='eat_fit_app.RecipeCategory', to='eat_fit_app.recipe'),
        ),
    ]
