# Generated by Django 4.2 on 2023-06-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_fit_app', '0002_recipe_instructions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='cuisine',
            options={'verbose_name_plural': 'Cuisines'},
        ),
        migrations.AlterModelOptions(
            name='ingredients',
            options={'ordering': ['name'], 'verbose_name_plural': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='occasion',
            options={'verbose_name_plural': 'Occasions'},
        ),
        migrations.AlterModelOptions(
            name='recipecategory',
            options={'verbose_name_plural': 'Recipe Categories'},
        ),
        migrations.AlterModelOptions(
            name='recipecuisine',
            options={'verbose_name_plural': 'Recipe Cuisines'},
        ),
        migrations.AlterModelOptions(
            name='recipeingredients',
            options={'verbose_name_plural': 'Recipe Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='recipeoccasion',
            options={'verbose_name_plural': 'Recipe Occasions'},
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.ManyToManyField(related_name='recipe_ingredients', to='eat_fit_app.recipeingredients'),
        ),
    ]
