# Generated by Django 4.2 on 2023-06-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eat_fit_app', '0003_alter_category_options_alter_cuisine_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='recipe_ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='recipe_ingredients',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
