# Generated by Django 4.2.1 on 2024-01-28 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eat_fit_app', '0007_recipe_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipe',
            options={'ordering': ['-created']},
        ),
        migrations.AlterField(
            model_name='occasion',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe_relation', to='eat_fit_app.ingredients'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='measure',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quantity_measurements', to='eat_fit_app.recipeingredientsmeasure'),
        ),
        migrations.AlterField(
            model_name='recipeingredients',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients_relation', to='eat_fit_app.recipe'),
        ),
    ]
