# Generated by Django 4.2.1 on 2024-01-09 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import image_handler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eat_fit_app', '0006_recipeingredientsmeasure_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('main_image', 'Main Image'), ('additional_image', 'Additional Image')], max_length=30)),
                ('description', models.TextField()),
                ('alt_description', models.CharField(blank=True, max_length=256, null=True)),
                ('image_file', models.ImageField(upload_to=image_handler.models.recipe_image_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipe', to='eat_fit_app.recipe')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_images', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
