# Generated by Django 4.2.1 on 2024-01-09 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eat_fit_app', '0006_recipeingredientsmeasure_and_more'),
        ('image_handler', '0002_alter_recipeimage_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recipe_images', to='eat_fit_app.recipe'),
        ),
    ]
