# Generated by Django 4.2.1 on 2024-01-28 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_handler', '0004_alter_recipeimage_alt_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeimage',
            name='alt_description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
